spring.application.name=Auth_microservice
# Keycloak config
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/Glud-web-dev
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9090/realms/Glud-web-dev/protocol/openid-connect/certs
#Keycloak debug configuration
logging.level.org.keycloak=DEBUG
#Jwt authentication variables configuration
jwt.auth.converter.principle-attribute=preferred_username
jwt.auth.converter.resouce-id=Glud-web-client-api